# Generated by Django 5.1.7 on 2025-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alternative',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
